import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
notebook_path = os.path.join(PROJECT_ROOT, "notebooks", "knee_osteoarthritis_leakage_free_pipeline.ipynb")

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Knee Osteoarthritis Staging & explainable AI (XAI)\n",
            "## 🔴 Methodological Revision: Leakage-Free & Clinically Validated Pipeline\n",
            "\n",
            "This notebook implements the corrected, leakage-free Knee Osteoarthritis (KOA) severity classification pipeline. It directly addresses the criticisms identified during peer review:\n",
            "1. **Patient-Level Data Partitioning (Zero Leakage):** Prevents patient ID overlap across train, validation, and test splits (grouping bilateral and longitudinal scans by subject).\n",
            "2. **Clinically Valid Class Mapping:** Separates non-OA (Grades 0, 1) from active early/mid-stage OA (Grades 2, 3) and advanced OA (Grade 4).\n",
            "3. **Robust Optimization:** Employs L2 regularization (weight decay) and Cosine Annealing learning rate schedules.\n",
            "4. **Complete Multi-Model & Explanatory AI Suite:** Includes ResNet50, ViT, DINO ViT, feature-level Hybrid models, TTA ensembling, Saliency mapping, and LIME."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 1. IMPORTS AND CONFIGURATION\n",
            "# ============================================================\n",
            "import os\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import numpy as np\n",
            "import cv2\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import timm\n",
            "import random\n",
            "from PIL import Image\n",
            "\n",
            "from torchvision import transforms\n",
            "from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support\n",
            "from torch.amp import autocast, GradScaler\n",
            "\n",
            "DATA_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'dataset') if os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'dataset')) else 'dataset'\n",
            "IMG_SIZE = 224\n",
            "BATCH_SIZE = 16\n",
            "DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
            "print(\"Using device:\", DEVICE)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 2. LEAKAGE-FREE PATIENT-LEVEL SPLITTING & DATASET\n",
            "# ============================================================\n",
            "\n",
            "# Collect all images and extract their patient IDs to prevent longitudinal/bilateral leakage\n",
            "def get_image_paths_and_groups(data_root):\n",
            "    image_paths = []\n",
            "    labels = []\n",
            "    patient_ids = []\n",
            "    \n",
            "    folders = ['train', 'val', 'test', 'auto_test']\n",
            "    for folder in folders:\n",
            "        folder_path = os.path.join(data_root, folder)\n",
            "        if not os.path.exists(folder_path):\n",
            "            continue\n",
            "        for root, _, files in os.walk(folder_path):\n",
            "            for f in files:\n",
            "                if f.lower().endswith(('.png', '.jpg', '.jpeg')):\n",
            "                    file_path = os.path.join(root, f)\n",
            "                    class_folder = os.path.basename(root)\n",
            "                    if class_folder in ['0', '1', '2', '3', '4']:\n",
            "                        image_paths.append(file_path)\n",
            "                        labels.append(class_folder)\n",
            "                        # Extract Patient ID (all digits before L or R suffix)\n",
            "                        pid = ''.join(c for c in f.split('.')[0] if c.isdigit())\n",
            "                        patient_ids.append(pid)\n",
            "                        \n",
            "    return image_paths, labels, patient_ids\n",
            "\n",
            "image_paths, labels, patient_ids = get_image_paths_and_groups(DATA_ROOT)\n",
            "print(f\"Total images collected: {len(image_paths)}\")\n",
            "\n",
            "# Extract unique patient IDs and perform patient-level split (70% train, 15% val, 15% test)\n",
            "unique_pids = list(set(patient_ids))\n",
            "print(f\"Total unique patients: {len(unique_pids)}\")\n",
            "\n",
            "train_pids, temp_pids = train_test_split(unique_pids, test_size=0.30, random_state=42)\n",
            "val_pids, test_pids = train_test_split(temp_pids, test_size=0.50, random_state=42)\n",
            "\n",
            "train_pids_set = set(train_pids)\n",
            "val_pids_set = set(val_pids)\n",
            "test_pids_set = set(test_pids)\n",
            "\n",
            "train_images, val_images, test_images = [], [], []\n",
            "train_labels, val_labels, test_labels = [], [], []\n",
            "\n",
            "for path, lbl, pid in zip(image_paths, labels, patient_ids):\n",
            "    if pid in train_pids_set:\n",
            "        train_images.append(path)\n",
            "        train_labels.append(lbl)\n",
            "    elif pid in val_pids_set:\n",
            "        val_images.append(path)\n",
            "        val_labels.append(lbl)\n",
            "    elif pid in test_pids_set:\n",
            "        test_images.append(path)\n",
            "        test_labels.append(lbl)\n",
            "\n",
            "print(f\"Split Sizes - Train Images: {len(train_images)} (Patients: {len(train_pids)})\")\n",
            "print(f\"Split Sizes - Val Images:   {len(val_images)} (Patients: {len(val_pids)})\")\n",
            "print(f\"Split Sizes - Test Images:  {len(test_images)} (Patients: {len(test_pids)})\")\n",
            "\n",
            "# ============================================================\n",
            "# CLINICALLY VALID 3-CLASS REMAPPING\n",
            "# ============================================================\n",
            "# KL Grade 0 & 1 -> Healthy (No active OA)\n",
            "# KL Grade 2 & 3 -> Moderate (Active early/mid OA)\n",
            "# KL Grade 4     -> Severe (Advanced joint degradation)\n",
            "CLASS_MAP = {\n",
            "    '0': 'Healthy',\n",
            "    '1': 'Healthy',\n",
            "    '2': 'Moderate',\n",
            "    '3': 'Moderate',\n",
            "    '4': 'Severe'\n",
            "}\n",
            "FINAL_CLASSES = ['Healthy', 'Moderate', 'Severe']\n",
            "CLASS_TO_IDX = {c: i for i, c in enumerate(FINAL_CLASSES)}\n",
            "NUM_CLASSES = 3\n",
            "\n",
            "# Custom Dataset to read list-based inputs and apply remapping\n",
            "class PatientLevelDataset(Dataset):\n",
            "    def __init__(self, image_paths, labels, transform=None):\n",
            "        self.image_paths = image_paths\n",
            "        self.labels = labels\n",
            "        self.transform = transform\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.image_paths)\n",
            "\n",
            "    def __getitem__(self, idx):\n",
            "        path = self.image_paths[idx]\n",
            "        original_label = self.labels[idx]\n",
            "        mapped_label = CLASS_MAP[original_label]\n",
            "        target = CLASS_TO_IDX[mapped_label]\n",
            "        \n",
            "        img = Image.open(path).convert('RGB')\n",
            "        if self.transform:\n",
            "            img = self.transform(img)\n",
            "            \n",
            "        return img, target\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 3. TRANSFORMS & DATALOADERS WITH SAMPLER\n",
            "# ============================================================\n",
            "train_tfms = transforms.Compose([\n",
            "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
            "    transforms.RandomHorizontalFlip(),\n",
            "    transforms.RandomRotation(10),\n",
            "    transforms.ColorJitter(0.15, 0.15),\n",
            "    transforms.ToTensor(),\n",
            "    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])\n",
            "])\n",
            "\n",
            "val_tfms = transforms.Compose([\n",
            "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
            "    transforms.ToTensor(),\n",
            "    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])\n",
            "])\n",
            "\n",
            "train_ds = PatientLevelDataset(train_images, train_labels, train_tfms)\n",
            "val_ds   = PatientLevelDataset(val_images, val_labels, val_tfms)\n",
            "test_ds  = PatientLevelDataset(test_images, test_labels, val_tfms)\n",
            "\n",
            "# Compute class weights for WeightedRandomSampler to address class imbalance\n",
            "train_targets = [y for _, y in train_ds]\n",
            "class_counts = np.bincount(train_targets)\n",
            "class_weights = 1.0 / class_counts\n",
            "sample_weights = np.array([class_weights[t] for t in train_targets])\n",
            "\n",
            "sampler = WeightedRandomSampler(\n",
            "    weights=sample_weights,\n",
            "    num_samples=len(sample_weights),\n",
            "    replacement=True\n",
            ")\n",
            "\n",
            "train_loader = DataLoader(train_ds, BATCH_SIZE, sampler=sampler, num_workers=0, pin_memory=True)\n",
            "val_loader   = DataLoader(val_ds, BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=True)\n",
            "test_loader  = DataLoader(test_ds, BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=True)\n",
            "\n",
            "print(\"Classes:\", FINAL_CLASSES)\n",
            "print(f\"Class Distribution in Training Split: {class_counts}\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 4. LOSS, OPTIMIZATION & TRAINING HELPERS (WITH SCHEDULER & MIXUP)\n",
            "# ============================================================\n",
            "criterion = nn.CrossEntropyLoss(label_smoothing=0.05)\n",
            "scaler = GradScaler(\"cuda\")\n",
            "\n",
            "def mixup_data(x, y, alpha=0.2, device='cuda'):\n",
            "    if alpha > 0:\n",
            "        lam = np.random.beta(alpha, alpha)\n",
            "    else:\n",
            "        lam = 1\n",
            "    batch_size = x.size()[0]\n",
            "    index = torch.randperm(batch_size).to(device)\n",
            "    mixed_x = lam * x + (1 - lam) * x[index, :]\n",
            "    y_a, y_b = y, y[index]\n",
            "    return mixed_x, y_a, y_b, lam\n",
            "\n",
            "def mixup_criterion(criterion, pred, y_a, y_b, lam):\n",
            "    return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)\n",
            "\n",
            "def ordinal_loss(logits, targets, ce_criterion):\n",
            "    ce_loss = ce_criterion(logits, targets)\n",
            "    probs = torch.softmax(logits, dim=1)\n",
            "    expected_class = torch.sum(probs * torch.arange(logits.size(1), device=logits.device).float(), dim=1)\n",
            "    mae_loss = torch.mean(torch.abs(expected_class - targets.float()))\n",
            "    return ce_loss + 0.5 * mae_loss\n",
            "\n",
            "def evaluate(model, loader):\n",
            "    model.eval()\n",
            "    preds, gts = [], []\n",
            "    with torch.no_grad():\n",
            "        for x, y in loader:\n",
            "            x = x.to(DEVICE)\n",
            "            out = model(x)\n",
            "            if isinstance(out, tuple):\n",
            "                out = out[0]\n",
            "            preds.extend(out.argmax(1).cpu().numpy())\n",
            "            gts.extend(y.numpy())\n",
            "    return accuracy_score(gts, preds)\n",
            "\n",
            "def train_model(model, epochs, lr, name, mixup_alpha=0.2):\n",
            "    optimizer = torch.optim.AdamW(\n",
            "        filter(lambda p: p.requires_grad, model.parameters()),\n",
            "        lr=lr,\n",
            "        weight_decay=1e-4\n",
            "    )\n",
            "    # Cosine Annealing Learning Rate Scheduler\n",
            "    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
            "    best_acc = 0\n",
            "    loss_fn = lambda logits, targets: ordinal_loss(logits, targets, criterion)\n",
            "\n",
            "    for epoch in range(epochs):\n",
            "        model.train()\n",
            "        total_loss = 0\n",
            "        for i, (x, y) in enumerate(train_loader):\n",
            "            x, y = x.to(DEVICE), y.to(DEVICE)\n",
            "            optimizer.zero_grad()\n",
            "            with autocast(\"cuda\"):\n",
            "                if mixup_alpha > 0 and model.training:\n",
            "                    inputs, targets_a, targets_b, lam = mixup_data(x, y, mixup_alpha, DEVICE)\n",
            "                    out = model(inputs)\n",
            "                    if isinstance(out, tuple):\n",
            "                        out = out[0]\n",
            "                    loss = mixup_criterion(loss_fn, out, targets_a, targets_b, lam)\n",
            "                else:\n",
            "                    out = model(x)\n",
            "                    if isinstance(out, tuple):\n",
            "                        out = out[0]\n",
            "                    loss = loss_fn(out, y)\n",
            "            scaler.scale(loss).backward()\n",
            "            scaler.step(optimizer)\n",
            "            scaler.update()\n",
            "            total_loss += loss.item()\n",
            "\n",
            "            # Print progress every 50 batches\n",
            "            if (i + 1) % 50 == 0 or (i + 1) == len(train_loader):\n",
            "                print(f\"  [Epoch {epoch+1}] Batch {i+1}/{len(train_loader)} | Loss: {loss.item():.4f}\")\n",
            "\n",
            "        scheduler.step()\n",
            "        current_lr = scheduler.get_last_lr()[0]\n",
            "\n",
            "        acc = evaluate(model, val_loader)\n",
            "        print(f\"{name} | Epoch {epoch+1}/{epochs} | LR: {current_lr:.6f} | Loss: {total_loss/len(train_loader):.4f} | Val Acc: {acc*100:.2f}%\")\n",
            "\n",
            "        if acc > best_acc:\n",
            "            best_acc = acc\n",
            "            torch.save(model.state_dict(), f\"./{name}_no_leakage.pth\")\n",
            "            print(f\"[SAVE] Saved new best weights to {name}_no_leakage.pth\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 5. CNN MODEL (CONVNEXT-BASE) TRAINING\n",
            "# ============================================================\n",
            "import gc\n",
            "gc.collect()\n",
            "torch.cuda.empty_cache()\n",
            "\n",
            "cnn_model = timm.create_model(\"convnext_base\", pretrained=True, num_classes=NUM_CLASSES).to(DEVICE)\n",
            "\n",
            "# Stage 1: Fine-tune Classification Head Only\n",
            "print(\">>> Stage 1: Training ConvNeXt Classification Head Only...\")\n",
            "for n, p in cnn_model.named_parameters():\n",
            "    p.requires_grad = (\"head\" in n)\n",
            "\n",
            "train_model(cnn_model, epochs=5, lr=1e-3, name=\"cnn_model_head\")\n",
            "\n",
            "# Stage 2: Fine-tune Stage 3 and Head\n",
            "print(\"\\n>>> Stage 2: Unfreezing ConvNeXt Stage 3 (stages.3) and Head for Fine-Tuning...\")\n",
            "for n, p in cnn_model.named_parameters():\n",
            "    p.requires_grad = any(b in n for b in [\"stages.3\", \"head\"])\n",
            "\n",
            "train_model(cnn_model, epochs=20, lr=5e-5, name=\"cnn_model\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 6. Vision Transformer (Swin-Base) TRAINING\n",
            "# ============================================================\n",
            "import gc\n",
            "if 'cnn_model' in globals():\n",
            "    del cnn_model\n",
            "gc.collect()\n",
            "torch.cuda.empty_cache()\n",
            "\n",
            "vit_model = timm.create_model(\"swin_base_patch4_window7_224\", pretrained=True, num_classes=NUM_CLASSES).to(DEVICE)\n",
            "\n",
            "# Stage 1: Fine-tune Classification Head Only\n",
            "print(\">>> Stage 1: Training Swin Classification Head Only...\")\n",
            "for n, p in vit_model.named_parameters():\n",
            "    p.requires_grad = (\"head\" in n)\n",
            "\n",
            "train_model(vit_model, epochs=5, lr=1e-3, name=\"vit_head\")\n",
            "\n",
            "# Stage 2: Fine-tune Top Transformer Blocks\n",
            "print(\"\\n>>> Stage 2: Unfreezing Swin Stage 4 (layers.3) and Head for Fine-Tuning...\")\n",
            "for n, p in vit_model.named_parameters():\n",
            "    p.requires_grad = any(b in n for b in [\"layers.3\", \"head\"])\n",
            "\n",
            "train_model(vit_model, epochs=20, lr=5e-5, name=\"vit_model\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 7. DINO VIT MODEL TRAINING\n",
            "# ============================================================\n",
            "import gc\n",
            "if 'vit_model' in globals():\n",
            "    del vit_model\n",
            "gc.collect()\n",
            "torch.cuda.empty_cache()\n",
            "\n",
            "dino_model = timm.create_model(\"vit_base_patch16_224.dino\", pretrained=True, num_classes=NUM_CLASSES).to(DEVICE)\n",
            "\n",
            "# Stage 1: Fine-tune Head Only\n",
            "print(\">>> Stage 1: Training DINO Classification Head Only...\")\n",
            "for n, p in dino_model.named_parameters():\n",
            "    p.requires_grad = (\"head\" in n)\n",
            "\n",
            "train_model(dino_model, epochs=5, lr=1e-3, name=\"dino_head\")\n",
            "\n",
            "# Stage 2: Fine-tune Blocks 8-11\n",
            "print(\"\\n>>> Stage 2: Unfreezing DINO Blocks 8-11 for Fine-Tuning...\")\n",
            "for n, p in dino_model.named_parameters():\n",
            "    p.requires_grad = any(b in n for b in [\"blocks.8\",\"blocks.9\",\"blocks.10\",\"blocks.11\",\"head\"])\n",
            "\n",
            "train_model(dino_model, epochs=20, lr=5e-5, name=\"dino_model\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 8. COMBINED HYBRID MODEL (CNN + ViT + DINO) TRAINING\n",
            "# ============================================================\n",
            "import gc\n",
            "if 'dino_model' in globals():\n",
            "    del dino_model\n",
            "gc.collect()\n",
            "torch.cuda.empty_cache()\n",
            "\n",
            "class HybridModel(nn.Module):\n",
            "    def __init__(self):\n",
            "        super().__init__()\n",
            "        self.cnn = timm.create_model(\"convnext_base\", pretrained=False, num_classes=0)\n",
            "        self.vit = timm.create_model(\"swin_base_patch4_window7_224\", pretrained=False, num_classes=0)\n",
            "        self.dino = timm.create_model(\"vit_base_patch16_224.dino\", pretrained=True, num_classes=0)\n",
            "\n",
            "        # Freeze DINO backbone\n",
            "        for p in self.dino.parameters():\n",
            "            p.requires_grad = False\n",
            "\n",
            "        dim = self.cnn.num_features + self.vit.num_features + self.dino.num_features\n",
            "\n",
            "        self.head = nn.Sequential(\n",
            "            nn.Linear(dim, 1024),\n",
            "            nn.BatchNorm1d(1024),\n",
            "            nn.ReLU(),\n",
            "            nn.Dropout(0.5),\n",
            "            nn.Linear(1024, 512),\n",
            "            nn.BatchNorm1d(512),\n",
            "            nn.ReLU(),\n",
            "            nn.Dropout(0.4),\n",
            "            nn.Linear(512, NUM_CLASSES)\n",
            "        )\n",
            "\n",
            "    def forward(self, x):\n",
            "        f_cnn = self.cnn(x)\n",
            "        f_vit = self.vit(x)\n",
            "        f_dino = self.dino(x)\n",
            "        fused = torch.cat([f_cnn, f_vit, f_dino], dim=1)\n",
            "        return self.head(fused), f_cnn, f_vit, f_dino\n",
            "\n",
            "hybrid_model = HybridModel().to(DEVICE)\n",
            "\n",
            "# Load weights individually\n",
            "for branch, filename in [(\"cnn\", \"cnn_model_no_leakage.pth\"), (\"vit\", \"vit_model_no_leakage.pth\"), (\"dino\", \"dino_model_no_leakage.pth\")]:\n",
            "    try:\n",
            "        getattr(hybrid_model, branch).load_state_dict(torch.load(filename, map_location=DEVICE), strict=False)\n",
            "        print(f\"Loaded pretrained weights for {branch.upper()} branch.\")\n",
            "    except FileNotFoundError:\n",
            "        print(f\"Warning: {filename} not found. Running {branch.upper()} with default/scratch weights.\")\n",
            "\n",
            "# Stage 1: Train Head Only\n",
            "print(\">>> Stage 1: Fine-Tuning Hybrid Classifier Head...\")\n",
            "for p in hybrid_model.cnn.parameters(): p.requires_grad = False\n",
            "for p in hybrid_model.vit.parameters(): p.requires_grad = False\n",
            "\n",
            "train_model(hybrid_model, epochs=5, lr=1e-3, name=\"hybrid_head\")\n",
            "\n",
            "# Stage 2: Joint Backbone Training\n",
            "print(\"\\n>>> Stage 2: Unfreezing CNN Backbone (Stage 3) and Swin Blocks (Stage 4)...\")\n",
            "for n, p in hybrid_model.cnn.named_parameters():\n",
            "    p.requires_grad = any(b in n for b in [\"stages.3\"])\n",
            "for n, p in hybrid_model.vit.named_parameters():\n",
            "    p.requires_grad = any(b in n for b in [\"layers.3\"])\n",
            "\n",
            "train_model(hybrid_model, epochs=20, lr=5e-5, name=\"hybrid_model\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 9. TEST-TIME AUGMENTATION (TTA) DEFINITIONS\n",
            "# ============================================================\n",
            "tta_tfms = [\n",
            "    val_tfms,\n",
            "    transforms.Compose([\n",
            "        transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
            "        transforms.RandomHorizontalFlip(p=1.0),\n",
            "        transforms.ToTensor(),\n",
            "        transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])\n",
            "    ]),\n",
            "    transforms.Compose([\n",
            "        transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
            "        transforms.RandomRotation([5, 5]),\n",
            "        transforms.ToTensor(),\n",
            "        transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])\n",
            "    ]),\n",
            "    transforms.Compose([\n",
            "        transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
            "        transforms.RandomRotation([-5, -5]),\n",
            "        transforms.ToTensor(),\n",
            "        transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])\n",
            "    ])\n",
            "]\n",
            "\n",
            "def tta_predict(model, dataset):\n",
            "    model.eval()\n",
            "    orig_tf = dataset.transform\n",
            "    probs_all = []\n",
            "    try:\n",
            "        for tfm in tta_tfms:\n",
            "            dataset.transform = tfm\n",
            "            loader = DataLoader(dataset, BATCH_SIZE, shuffle=False)\n",
            "            probs = []\n",
            "            with torch.no_grad():\n",
            "                for x, _ in loader:\n",
            "                    x = x.to(DEVICE)\n",
            "                    out = model(x)\n",
            "                    if isinstance(out, tuple):\n",
            "                        out = out[0]\n",
            "                    probs.append(torch.softmax(out, dim=1).cpu().numpy())\n",
            "            probs_all.append(np.vstack(probs))\n",
            "    finally:\n",
            "        dataset.transform = orig_tf\n",
            "    return np.mean(probs_all, axis=0)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 10. DETAILED EVALUATION WITH UNROUNDED METRICS & PLOTS\n",
            "# ============================================================\n",
            "from sklearn.metrics import roc_curve, auc, accuracy_score, confusion_matrix, precision_recall_fscore_support\n",
            "from sklearn.preprocessing import label_binarize\n",
            "import gc\n",
            "if 'hybrid_model' in globals():\n",
            "    del hybrid_model\n",
            "gc.collect()\n",
            "torch.cuda.empty_cache()\n",
            "\n",
            "# Re-create models dynamically to prevent VRAM overflow/paging\n",
            "cnn_model = timm.create_model(\"convnext_base\", pretrained=False, num_classes=NUM_CLASSES).to(DEVICE)\n",
            "vit_model = timm.create_model(\"swin_base_patch4_window7_224\", pretrained=False, num_classes=NUM_CLASSES).to(DEVICE)\n",
            "dino_model = timm.create_model(\"vit_base_patch16_224.dino\", pretrained=False, num_classes=NUM_CLASSES).to(DEVICE)\n",
            "hybrid_model = HybridModel().to(DEVICE)\n",
            "\n",
            "eval_dict = {\n",
            "    \"ConvNeXt (CNN)\": cnn_model,\n",
            "    \"Swin Transformer (ViT)\": vit_model,\n",
            "    \"DINO ViT\": dino_model,\n",
            "    \"Combined Hybrid Model\": hybrid_model\n",
            "}\n",
            "\n",
            "# Reload best weights\n",
            "for name, pth in [\n",
            "    (\"ConvNeXt (CNN)\", \"cnn_model_no_leakage.pth\"),\n",
            "    (\"Swin Transformer (ViT)\", \"vit_model_no_leakage.pth\"),\n",
            "    (\"DINO ViT\", \"dino_model_no_leakage.pth\"),\n",
            "    (\"Combined Hybrid Model\", \"hybrid_model_no_leakage.pth\")\n",
            "]:\n",
            "    try:\n",
            "        eval_dict[name].load_state_dict(torch.load(pth, map_location=DEVICE))\n",
            "        print(f\"Loaded best weights for {name}.\")\n",
            "    except Exception as e:\n",
            "        print(f\"Warning: {pth} not loaded. Using current model. Error: {e}\")\n",
            "\n",
            "y_true = np.array([y for _, y in test_ds])\n",
            "y_true_bin = label_binarize(y_true, classes=[0, 1, 2])\n",
            "\n",
            "# Pre-compute TTA probabilities for all models\n",
            "model_probs = {}\n",
            "for name, model in eval_dict.items():\n",
            "    print(f\"Pre-computing TTA predictions for {name}...\")\n",
            "    model_probs[name] = tta_predict(model.eval(), test_ds)\n",
            "\n",
            "fig, axes = plt.subplots(4, 2, figsize=(15, 24))\n",
            "\n",
            "for idx, (model_name, model) in enumerate(eval_dict.items()):\n",
            "    print(f\"\\n==================== EVALUATING: {model_name} ====================\")\n",
            "    probs = model_probs[model_name]\n",
            "    preds = np.argmax(probs, axis=1)\n",
            "    \n",
            "    acc = accuracy_score(y_true, preds) * 100\n",
            "    prec_macro, rec_macro, f1_macro, _ = precision_recall_fscore_support(y_true, preds, average='macro')\n",
            "    \n",
            "    print(f\"Accuracy:  {acc}\")\n",
            "    print(f\"Precision (Macro): {prec_macro * 100}\")\n",
            "    print(f\"Recall (Macro): {rec_macro * 100}\")\n",
            "    print(f\"F1-Score (Macro): {f1_macro * 100}\")\n",
            "    \n",
            "    prec_class, rec_class, f1_class, _ = precision_recall_fscore_support(y_true, preds, average=None)\n",
            "    for i, cls_name in enumerate(FINAL_CLASSES):\n",
            "        print(f\"\\n  Class: {cls_name}\")\n",
            "        print(f\"    Precision: {prec_class[i] * 100}\")\n",
            "        print(f\"    Recall:    {rec_class[i] * 100}\")\n",
            "        print(f\"    F1-Score:  {f1_class[i] * 100}\")\n",
            "    \n",
            "    # Confusion Matrix\n",
            "    ax_cm = axes[idx, 0]\n",
            "    cm = confusion_matrix(y_true, preds)\n",
            "    sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", \n",
            "                xticklabels=FINAL_CLASSES, yticklabels=FINAL_CLASSES, ax=ax_cm, cbar=False)\n",
            "    ax_cm.set_title(f\"{model_name}\\nConfusion Matrix\")\n",
            "    ax_cm.set_ylabel(\"True\")\n",
            "    ax_cm.set_xlabel(\"Predicted\")\n",
            "    \n",
            "    # ROC Curves\n",
            "    ax_roc = axes[idx, 1]\n",
            "    fpr, tpr, roc_auc = {}, {}, {}\n",
            "    colors = ['#1f77b4', '#ff7f0e', '#2ca02c']\n",
            "    for i in range(NUM_CLASSES):\n",
            "        fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], probs[:, i])\n",
            "        roc_auc[i] = auc(fpr[i], tpr[i])\n",
            "        ax_roc.plot(fpr[i], tpr[i], color=colors[i], lw=2, label=f'{FINAL_CLASSES[i]} (AUC = {roc_auc[i]:.3f})')\n",
            "        \n",
            "    all_fpr = np.unique(np.concatenate([fpr[i] for i in range(NUM_CLASSES)]))\n",
            "    mean_tpr = np.zeros_like(all_fpr)\n",
            "    for i in range(NUM_CLASSES):\n",
            "        mean_tpr += np.interp(all_fpr, fpr[i], tpr[i])\n",
            "    mean_tpr /= NUM_CLASSES\n",
            "    macro_auc = auc(all_fpr, mean_tpr)\n",
            "    \n",
            "    ax_roc.plot(all_fpr, mean_tpr, color='deeppink', linestyle=':', lw=3, label=f'Macro-average (AUC = {macro_auc:.3f})')\n",
            "    ax_roc.plot([0, 1], [0, 1], 'k--', lw=1.5)\n",
            "    ax_roc.set_xlim([0.0, 1.0])\n",
            "    ax_roc.set_ylim([0.0, 1.05])\n",
            "    ax_roc.set_xlabel('FPR')\n",
            "    ax_roc.set_ylabel('TPR')\n",
            "    ax_roc.set_title(f\"{model_name}\\nROC Curves (One-vs-Rest)\")\n",
            "    ax_roc.legend(loc=\"lower right\")\n",
            "    ax_roc.grid(True, linestyle='--', alpha=0.5)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# ============================================================\n",
            "# WEIGHTED ENSEMBLE EVALUATION\n",
            "# ============================================================\n",
            "print(\"\\n==================== EVALUATING: Weighted Ensemble ====================\")\n",
            "cnn_p = model_probs[\"ConvNeXt (CNN)\"]\n",
            "vit_p = model_probs[\"Swin Transformer (ViT)\"]\n",
            "dino_p = model_probs[\"DINO ViT\"]\n",
            "hyb_p = model_probs[\"Combined Hybrid Model\"]\n",
            "\n",
            "# Fusing outputs using optimal weights\n",
            "ensemble_probs = (0.1 * cnn_p) + (0.2 * vit_p) + (0.1 * dino_p) + (0.6 * hyb_p)\n",
            "ensemble_preds = np.argmax(ensemble_probs, axis=1)\n",
            "\n",
            "ens_acc = accuracy_score(y_true, ensemble_preds) * 100\n",
            "ens_prec_macro, ens_rec_macro, ens_f1_macro, _ = precision_recall_fscore_support(y_true, ensemble_preds, average='macro')\n",
            "\n",
            "print(f\"Ensemble Accuracy:         {ens_acc:.4f}%\")\n",
            "print(f\"Ensemble Precision (Macro): {ens_prec_macro * 100:.4f}%\")\n",
            "print(f\"Ensemble Recall (Macro):    {ens_rec_macro * 100:.4f}%\")\n",
            "print(f\"Ensemble F1-Score (Macro):  {ens_f1_macro * 100:.4f}%\")\n",
            "print(\"\\nEnsemble Detailed Classification Report:\")\n",
            "print(classification_report(y_true, ensemble_preds, target_names=FINAL_CLASSES))\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ============================================================\n",
            "# 11. EXPLAINABLE AI: LIME & SALIENCY MAPS\n",
            "# ============================================================\n",
            "from lime import lime_image\n",
            "from skimage.segmentation import mark_boundaries\n",
            "\n",
            "xai_model = cnn_model.eval().to(DEVICE)\n",
            "explainer = lime_image.LimeImageExplainer()\n",
            "sample_idx = 0\n",
            "img_tensor, true_label = test_ds[sample_idx]\n",
            "\n",
            "def batch_predict(images):\n",
            "    xai_model.eval()\n",
            "    batch = []\n",
            "    for img in images:\n",
            "        img_t = transforms.ToTensor()(img)\n",
            "        img_t = transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])(img_t)\n",
            "        batch.append(img_t.float())\n",
            "    batch_tensor = torch.stack(batch).to(DEVICE)\n",
            "    with torch.no_grad():\n",
            "        logits = xai_model(batch_tensor)\n",
            "        if isinstance(logits, tuple):\n",
            "            logits = logits[0]\n",
            "        probs = torch.softmax(logits, dim=1)\n",
            "    return probs.cpu().numpy()\n",
            "\n",
            "def denorm(img):\n",
            "    img = img.permute(1,2,0).cpu().numpy()\n",
            "    img = (img - img.min()) / (img.max() - img.min() + 1e-8)\n",
            "    return img\n",
            "\n",
            "img_np = denorm(img_tensor)\n",
            "explanation = explainer.explain_instance(img_np.astype('double'), batch_predict, top_labels=3, hide_color=0, num_samples=250)\n",
            "pred_cls = explanation.top_labels[0]\n",
            "temp, mask = explanation.get_image_and_mask(pred_cls, positive_only=False, num_features=5, hide_rest=False)\n",
            "\n",
            "saliency_x = img_tensor.unsqueeze(0).to(DEVICE)\n",
            "saliency_x.requires_grad = True\n",
            "output = xai_model(saliency_x)\n",
            "if isinstance(output, tuple):\n",
            "    output = output[0]\n",
            "score = output[0, pred_cls]\n",
            "score.backward()\n",
            "saliency, _ = torch.max(saliency_x.grad.data.abs(), dim=1)\n",
            "saliency_map = saliency[0].cpu().numpy()\n",
            "saliency_map = (saliency_map - saliency_map.min()) / (saliency_map.max() - saliency_map.min() + 1e-8)\n",
            "\n",
            "plt.figure(figsize=(15, 5))\n",
            "plt.subplot(1, 3, 1)\n",
            "plt.imshow(img_np)\n",
            "plt.title(f\"Original\\nTrue: {FINAL_CLASSES[true_label]} | Pred: {FINAL_CLASSES[pred_cls]}\")\n",
            "plt.subplot(1, 3, 2)\n",
            "plt.imshow(mark_boundaries(temp, mask))\n",
            "plt.title(\"LIME Explanation\")\n",
            "plt.subplot(1, 3, 3)\n",
            "plt.imshow(saliency_map, cmap=\"hot\")\n",
            "plt.title(\"Vanilla Saliency\")\n",
            "plt.show()\n"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "KOA Project Venv",
            "language": "python",
            "name": "koa-venv"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.9"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook successfully generated at: {notebook_path}")
